---
title: "Homework 9"
author: "Emma"
date: "2023-04-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Link to Repository: https://github.com/epodlich/homework9

## Part One: Data Tidying

```{r}
library(tidyverse)

av <- read.csv("https://raw.githubusercontent.com/fivethirtyeight/data/master/avengers/avengers.csv", stringsAsFactors = FALSE)

View(av)

```

```{r}
names(av)

av0 = av %>% filter(Name.Alias != "")

av1 = av0 %>% gather(key = time, value = death, c(11, 13, 15, 17, 19)) %>% 
  select(Name.Alias, time, death) %>%
  mutate(time = parse_number(time))
View(av1)

av2 = av0 %>% gather(key = time, value = return, c(12, 14, 16, 18, 20)) %>% 
  select(Name.Alias, time, return) %>%
  mutate(time = parse_number(time))
View(av2)

death = left_join(av1, av2, by = c("Name.Alias", "time"))
View(death)
```

```{r}
av0 = av0 %>% filter(Name.Alias != "Vance Astrovik")
av1 = av0 %>% gather(key = time, value = death, c(11, 13, 15, 17, 19)) %>%
  select(Name.Alias, time, death) %>%
  mutate(time = parse_number(time))
av2 = av0 %>% gather(key = time, value = return, c(12, 14, 16, 18, 20)) %>% 
  select(Name.Alias, time, return) %>%
  mutate(time = parse_number(time))
av.neat = left_join(av1, av2, by = c("Name.Alias", "time"))

av.neat %>% filter(time == 1, death == "YES") %>%
  summarise(total.num = n(),
            real.return = sum(return == "YES"),
            fake.return = sum(return == "NO"),
            missing = sum(return == ""))

```


## Part Two: Validation

### Emma

Statement Validation from FiveThirtyEight:

"I counted 89 total deaths — some unlucky Avengers7 are basically Meat Loaf with an E-ZPass — and on 57 occasions the individual made a comeback."

```{r}
death %>% filter(death == "YES" | return == "YES") %>% summarise(total_death = sum(death == "YES"), comeback = sum(return == "YES"))

# The FiveThirtyEight statement said that there were 89 total deaths and 57 of them made comebacks. When we analyzed our data set, we found that there where 82 total deaths and 55 of them made comebacks. This is slightly off from the FiveThirtyEight statement but the values are quite close so there may have just been some kind of counting error. Or, we are using slightly different data sets.
```

